name: Package and Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the codebase from the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup the appropriate .NET Core SDK version for the build environment
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      # Build the solution
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      # Package the bindings project for release to NuGet
      - name: Create the package
        run: dotnet pack --configuration Release CT.CASE.Bindings
      
      # Publish the created bindings .nupkg file to NuGet
      - name: Publish to nuget.org
        run: dotnet nuget push CT.CASE.Bindings/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}